---
- hosts: local
  become: yes  # Use this if elevated privileges are required
  tasks:
  
    #Create/Overwrite the file
  - name: Create or overwrite the script file
    copy:
      dest: /home/bahe/tmp/newtext.sh
      content: |
        #!/bin/bash
        echo "Hello, this is a sample script"
  
    #Permissions for the file
  - name: Set executable permissions for the script
    file:
      path: /home/bahe/tmp/newtext.sh
      mode: '0755'
      state: file
 
    #Append in file
  - name: Append the file
    ansible.builtin.blockinfile:
      path: /home/bahe/tmp/newtext.sh
      both: |
        Addending line 1
        Addending line 2
        Addending line 3
    
    #remove
    #find and replace
     
